### ISSUE TITLE
0元购BUG 显示空白BUG （使用了SQL数据库）

### ISSUE THREAD

**Issue by jiajiaxd** [Fireflyest/GlobalMarket#2]
输入指令/mk sell 10
但是上架的实际上是0元（无报错）
![1](https://user-images.githubusercontent.com/51043917/183864390-fde9e0e2-94dc-4f00-95d8-087c1dd90879.gif)
第二个bug是 上架的物品是空白 但是却可以点开
输入/mk时后台的报错：
```
[17:16:47 WARN] [CraftGUI]: Plugin CraftGUI v1.0.10 generated an exception while executing task 4446
com.google.gson.JsonSyntaxException: com.google.gson.stream.MalformedJsonException: Unterminated object at line 1 column 46 path $.
        at com.google.gson.Gson.fromJson(Gson.java:978) ~[gson-2.8.9.jar%2321!/:?]
        at com.google.gson.Gson.fromJson(Gson.java:928) ~[gson-2.8.9.jar%2321!/:?]
        at com.google.gson.Gson.fromJson(Gson.java:877) ~[gson-2.8.9.jar%2321!/:?]
        at org.fireflyest.craftgui.util.SerializeUtil.deserialize(SerializeUtil.java:120) ~[?:?]
        at com.fireflyest.market.view.MainPage.getItemMap(MainPage.java:106) ~[?:?]
        at org.fireflyest.craftgui.protocol.ViewProtocol$2.run(ViewProtocol.java:155) ~[?:?]
        at org.bukkit.craftbukkit.v1_18_R2.scheduler.CraftTask.run(CraftTask.java:82) ~[arclight-1.18.2-1.0.6-7e754e7e.jar%2368!/:arclight-1.18.2-1.0.6-7e754e7e]
        at org.bukkit.craftbukkit.v1_18_R2.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54) [arclight-1.18.2-1.0.6-7e754e7e.jar%2368!/:arclight-1.18.2-1.0.6-7e754e7e]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) [?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) [?:?]
        at java.lang.Thread.run(Thread.java:833) [?:?]
Caused by: com.google.gson.stream.MalformedJsonException: Unterminated object at line 1 column 46 path $.
        at com.google.gson.stream.JsonReader.syntaxError(JsonReader.java:1562) ~[gson-2.8.9.jar%2321!/:?]
        at com.google.gson.stream.JsonReader.doPeek(JsonReader.java:490) ~[gson-2.8.9.jar%2321!/:?]
        at com.google.gson.stream.JsonReader.hasNext(JsonReader.java:413) ~[gson-2.8.9.jar%2321!/:?]
        at com.google.gson.internal.bind.MapTypeAdapterFactory$Adapter.read(MapTypeAdapterFactory.java:184) ~[gson-2.8.9.jar%2321!/:?]
        at com.google.gson.internal.bind.MapTypeAdapterFactory$Adapter.read(MapTypeAdapterFactory.java:145) ~[gson-2.8.9.jar%2321!/:?]
        at com.google.gson.Gson.fromJson(Gson.java:963) ~[gson-2.8.9.jar%2321!/:?]
        ... 10 more
```

**Comment by Fireflyest** [comment]
在config.yml 设置debug为true再上架，才有详细的报错

**Comment by jiajiaxd** [comment]
出售时确实没有报错

**Comment by Fireflyest** [comment]
是存在一些sqlite和mysql之间的差异，我已做了适配，这边测试没问题了，请更新到市场v3.2.6 GUI 1.0.11

**Comment by jiajiaxd** [comment]
BUG已经全部解决 感谢帮助
还有我想问一下：怎么卖Points物品？/mk sell 貌似默认是Vault
config.yml里已经开了点券交易

**Comment by Fireflyest** [comment]
使用/mk point指令，或者快捷上架之后编辑商品。我这边又发现一个bug，物品属性太长会造成数据库meta字段长度不够，目前已经修复，准备更新。你也可以手动更改数据库字段长度，或者利用新版重新建表

**Comment by jiajiaxd** [comment]
好的，建议将mk point命令加到帮助菜单里.

**Comment by jiajiaxd** [comment]
貌似建表还是有点问题
报错：
```
[14:45:16 ERROR] [STDERR]: com.mysql.cj.jdbc.exceptions.MysqlDataTruncation: Data truncation: Data too long for column 'meta' at row 1
[14:45:16 ERROR] [STDERR]:      at MC-BOOTSTRAP/mysql.connector.java@8.0.27/com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:104)
[14:45:16 ERROR] [STDERR]:      at MC-BOOTSTRAP/mysql.connector.java@8.0.27/com.mysql.cj.jdbc.ClientPreparedStatement.executeInternal(ClientPreparedStatement.java:953)
[14:45:16 ERROR] [STDERR]:      at MC-BOOTSTRAP/mysql.connector.java@8.0.27/com.mysql.cj.jdbc.ClientPreparedStatement.executeUpdateInternal(ClientPreparedStatement.java:1098)
[14:45:16 ERROR] [STDERR]:      at MC-BOOTSTRAP/mysql.connector.java@8.0.27/com.mysql.cj.jdbc.ClientPreparedStatement.executeUpdateInternal(ClientPreparedStatement.java:1046)
[14:45:16 ERROR] [STDERR]:      at MC-BOOTSTRAP/mysql.connector.java@8.0.27/com.mysql.cj.jdbc.ClientPreparedStatement.executeLargeUpdate(ClientPreparedStatement.java:1371)
[14:45:16 ERROR] [STDERR]:      at MC-BOOTSTRAP/mysql.connector.java@8.0.27/com.mysql.cj.jdbc.ClientPreparedStatement.executeUpdate(ClientPreparedStatement.java:1031)
[14:45:16 ERROR] [STDERR]:      at com.fireflyest.market.sql.SqlStorage.insert(SqlStorage.java:103)
[14:45:16 ERROR] [STDERR]:      at com.fireflyest.market.sql.SqlData.insert(SqlData.java:85)
[14:45:16 ERROR] [STDERR]:      at com.fireflyest.market.core.MarketManager.addMail(MarketManager.java:121)
[14:45:16 ERROR] [STDERR]:      at com.fireflyest.market.task.TaskSend.execute(TaskSend.java:47)
[14:45:16 ERROR] [STDERR]:      at com.fireflyest.market.task.TaskHandler.loop(TaskHandler.java:98)
[14:45:16 ERROR] [STDERR]:      at com.fireflyest.market.task.TaskHandler$1.run(TaskHandler.java:28)
[14:45:16 ERROR] [STDERR]:      at TRANSFORMER/arclight@1.18.2-1.0.6-7e754e7e/org.bukkit.craftbukkit.v1_18_R2.scheduler.CraftTask.run(CraftTask.java:82)
[14:45:16 ERROR] [STDERR]:      at TRANSFORMER/arclight@1.18.2-1.0.6-7e754e7e/org.bukkit.craftbukkit.v1_18_R2.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54)
[14:45:16 ERROR] [STDERR]:      at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
[14:45:16 ERROR] [STDERR]:      at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
[14:45:16 ERROR] [STDERR]:      at java.base/java.lang.Thread.run(Thread.java:833)
```
我用navicat看数据表长度，是空的：
![image](https://user-images.githubusercontent.com/51043917/184078724-696b5ae2-0572-4c02-809b-1defe01dcbeb.png)

**Comment by Fireflyest** [comment]
text类型是没有长度的
我这边显示是0而且可以正常使用
生成的建表sql是
```sql
create table if not exists `sale`(`id` int primary key not null auto_increment,`stack` varchar(1024),`meta` text,`nbt` varchar(1024),`appear` bigint,`owner` varchar(1024),`buyer` varchar(1024),`price` decimal,`cost` decimal,`heat` int,`nickname` varchar(1024),`desc` varchar(1024),`classify` varchar(1024),`auction` bit,`point` bit,`admin` bit);
```
貌似是版本问题还是什么，我不太清楚

**Comment by jiajiaxd** [comment]
还有一个BUG 拍卖显示的永远是第0次叫价

**Comment by Fireflyest** [comment]
拍卖是在最后一个人出价后，每半个小时叫一次价。当有新的参与时，叫价变成0重新开始。第三次叫价时完成竞拍。
每次叫价都会通知所有参与的人（叫价三次定价完成拍卖）

**Comment by Fireflyest** [comment]
是菜单里面按钮文字错了，应该是出价不是叫价

**Comment by jiajiaxd** [comment]
是不支持XConomy吗？买了东西之后只扣钱
卖家不会收到钱

**Comment by Fireflyest** [comment]
卖家在邮箱收交易记录的时候才能得到钱

**Comment by jiajiaxd** [comment]
？收交易记录？点那个
![image](https://user-images.githubusercontent.com/51043917/184087819-528e903a-c814-4565-8b87-3e7ed4584f72.png)

**Comment by jiajiaxd** [comment]
还有BUG==就是上架0.01元的商品，会显示成0.0元
